version: '3'
services:
    alphp:
        image: swoft/alphp:dev
        environment:
            - APP_ENV=dev
        links:
            - mysql
            - redis
        ports:
            - "10080:80"
            - "19501:9501"
        volumes:
            - ./:/var/www
            - ./tmp/ng-conf:/etc/nginx
            - ./tmp/logs:/var/log

    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "13306:3306"
        volumes:
            - ./tmp/data/mysql:/var/lib/mysql

    redis:
        image: redis:3-alpine
