version: '3'
services:
    alfpm:
        image: swoft/alphp:fpm
        environment:
            TZ: Asia/Shanghai
            APP_ENV: dev
        volumes:
            - ../:/data # source code
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/app-vhost:/etc/nginx/conf.d/default.conf # doc restart nginx -> take effect
            - ./config/fpm.www.conf:/etc/php7/php-fpm.d/www.conf
            - ./config/php.www.ini:/etc/php7/conf.d/www.ini
            - ./logs/nginx:/var/log/nginx
            - ./logs/fpm:/var/log/php7
        ports:
           - "80:80"
           - "443:443"
        links:
            - mysql
            - redis
        extra_hosts:
             - "fpm:127.0.0.1"
             
    alphp:
        image: swoft/alphp:dev
        container_name: php-svr
        environment:
            - APP_ENV=dev
        links:
            - mysql
            - redis
        ports:
            - "10080:80"
            - "19501:9501"
        volumes:
            - ./:/var/www
            # - ./tmp/ng-conf:/etc/nginx
            # - ./tmp/logs:/var/log

    mysql:
        image: mysql
        container_name: mysql-svr
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "13306:3306"
        volumes:
            - ./tmp/data/mysql:/var/lib/mysql

    redis:
        container_name: redis-svr
        image: redis:4-alpine
        ports:
            - "16379:6379"
