version: '3'
services:
    alphp:
        image: swoft/alphp:dev
        container_name: php-svr
        environment:
            - APP_ENV=dev
        links:
            - mysql
            - redis
        ports:
            - "10080:80"
            - "19501:9501"
        volumes:
            - ./:/var/www
            # - ./tmp/ng-conf:/etc/nginx
            # - ./tmp/logs:/var/log

    mysql:
        image: mysql
        container_name: mysql-svr
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "13306:3306"
        volumes:
            - ./tmp/data/mysql:/var/lib/mysql

    redis:
        container_name: redis-svr
        image: redis:4-alpine
        ports:
            - "16379:6379"
